# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flut',
            old_name='flut_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='flut',
            old_name='flut_time',
            new_name='time',
        ),
    ]
