# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0004_auto_20160913_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flut',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
