# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_todo', '0002_auto_20160831_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subitem',
            name='main_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='sub_todo.MainItem'),
        ),
    ]
